#!/bin/bash
certbot certonly \
  --manual \
  --preferred-challenges dns \
  --manual-auth-hook "/usr/local/bin/ncloud-certbot-hook --hook=auth" \
  --manual-cleanup-hook "/usr/local/bin/ncloud-certbot-hook --hook=cleanup" \
  --deploy-hook "/usr/local/bin/ncloud-certbot-hook --hook=deploy" \
  --non-interactive --agree-tos --manual-public-ip-logging-ok \
  "$@"